// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { add } from "./add.js";
import { addAll } from "./addAll.js";
import { assert } from "./assert.js";
import { difference } from "./difference.js";
import { Flag } from "./types.js";
import { fromRecord } from "./fromRecord.js";
import { has } from "./has.js";
import { hasAll } from "./hasAll.js";
import { hasAny } from "./hasAny.js";
import { hasNone } from "./hasNone.js";
import { intersection } from "./intersection.js";
import { invert } from "./invert.js";
import { isDisjointFrom } from "./isDisjointFrom.js";
import { isSubsetOf } from "./isSubsetOf.js";
import { isSupersetOf } from "./isSupersetOf.js";
import { isValid } from "./isValid.js";
import { remove } from "./remove.js";
import { removeAll } from "./removeAll.js";
import { symmetricDifference } from "./symmetricDifference.js";
import { toggle } from "./toggle.js";
import { toggleAll } from "./toggleAll.js";
import { toRecord } from "./toRecord.js";
import { union } from "./union.js";

declare namespace Flags {
    export {
        add,
        addAll,
        assert,
        difference,
        fromRecord,
        has,
        hasAll,
        hasAny,
        hasNone,
        intersection,
        invert,
        isDisjointFrom,
        isSubsetOf,
        isSupersetOf,
        isValid,
        remove,
        removeAll,
        symmetricDifference,
        toggle,
        toggleAll,
        toRecord,
        union,
    }
}

export {
    Flags,
    Flag,
}
